brew "apache-arrow"
brew "autoconf-archive"
brew "automake"
brew "bison"
brew "coreutils"
# brew "cutter"
brew "libevent"
brew "libtool"
brew "mecab"
brew "mecab-ipadic"
brew "msgpack"
brew "openssl"
brew "pcre"
brew "pkg-config"
brew "python"
brew "rapidjson"
