.. -*- rst -*-

.. note::

   ``groonga`` package is the minimum set of fulltext search engine.
   If you want to use Groonga for server use, you can install
   additional preconfigured packages.

   There are two packages for server use.

   * groonga-httpd (nginx and HTTP protocol based server package)
   * groonga-server-gqtp (GQTP protocol based server package)

   See :doc:`/server` section about details.
