#define GRN_EXPR_TOKEN_LOGICAL_AND                     1
#define GRN_EXPR_TOKEN_LOGICAL_AND_NOT                 2
#define GRN_EXPR_TOKEN_LOGICAL_OR                      3
#define GRN_EXPR_TOKEN_QSTRING                         4
#define GRN_EXPR_TOKEN_PARENL                          5
#define GRN_EXPR_TOKEN_PARENR                          6
#define GRN_EXPR_TOKEN_RELATIVE_OP                     7
#define GRN_EXPR_TOKEN_IDENTIFIER                      8
#define GRN_EXPR_TOKEN_BRACEL                          9
#define GRN_EXPR_TOKEN_BRACER                         10
#define GRN_EXPR_TOKEN_EVAL                           11
#define GRN_EXPR_TOKEN_COMMA                          12
#define GRN_EXPR_TOKEN_ASSIGN                         13
#define GRN_EXPR_TOKEN_STAR_ASSIGN                    14
#define GRN_EXPR_TOKEN_SLASH_ASSIGN                   15
#define GRN_EXPR_TOKEN_MOD_ASSIGN                     16
#define GRN_EXPR_TOKEN_PLUS_ASSIGN                    17
#define GRN_EXPR_TOKEN_MINUS_ASSIGN                   18
#define GRN_EXPR_TOKEN_SHIFTL_ASSIGN                  19
#define GRN_EXPR_TOKEN_SHIFTR_ASSIGN                  20
#define GRN_EXPR_TOKEN_SHIFTRR_ASSIGN                 21
#define GRN_EXPR_TOKEN_AND_ASSIGN                     22
#define GRN_EXPR_TOKEN_XOR_ASSIGN                     23
#define GRN_EXPR_TOKEN_OR_ASSIGN                      24
#define GRN_EXPR_TOKEN_QUESTION                       25
#define GRN_EXPR_TOKEN_COLON                          26
#define GRN_EXPR_TOKEN_BITWISE_OR                     27
#define GRN_EXPR_TOKEN_BITWISE_XOR                    28
#define GRN_EXPR_TOKEN_BITWISE_AND                    29
#define GRN_EXPR_TOKEN_EQUAL                          30
#define GRN_EXPR_TOKEN_NOT_EQUAL                      31
#define GRN_EXPR_TOKEN_LESS                           32
#define GRN_EXPR_TOKEN_GREATER                        33
#define GRN_EXPR_TOKEN_LESS_EQUAL                     34
#define GRN_EXPR_TOKEN_GREATER_EQUAL                  35
#define GRN_EXPR_TOKEN_IN                             36
#define GRN_EXPR_TOKEN_MATCH                          37
#define GRN_EXPR_TOKEN_NEAR                           38
#define GRN_EXPR_TOKEN_NEAR2                          39
#define GRN_EXPR_TOKEN_SIMILAR                        40
#define GRN_EXPR_TOKEN_TERM_EXTRACT                   41
#define GRN_EXPR_TOKEN_LCP                            42
#define GRN_EXPR_TOKEN_PREFIX                         43
#define GRN_EXPR_TOKEN_SUFFIX                         44
#define GRN_EXPR_TOKEN_SHIFTL                         45
#define GRN_EXPR_TOKEN_SHIFTR                         46
#define GRN_EXPR_TOKEN_SHIFTRR                        47
#define GRN_EXPR_TOKEN_PLUS                           48
#define GRN_EXPR_TOKEN_MINUS                          49
#define GRN_EXPR_TOKEN_STAR                           50
#define GRN_EXPR_TOKEN_SLASH                          51
#define GRN_EXPR_TOKEN_MOD                            52
#define GRN_EXPR_TOKEN_DELETE                         53
#define GRN_EXPR_TOKEN_INCR                           54
#define GRN_EXPR_TOKEN_DECR                           55
#define GRN_EXPR_TOKEN_NOT                            56
#define GRN_EXPR_TOKEN_BITWISE_NOT                    57
#define GRN_EXPR_TOKEN_ADJUST                         58
#define GRN_EXPR_TOKEN_EXACT                          59
#define GRN_EXPR_TOKEN_PARTIAL                        60
#define GRN_EXPR_TOKEN_UNSPLIT                        61
#define GRN_EXPR_TOKEN_DECIMAL                        62
#define GRN_EXPR_TOKEN_HEX_INTEGER                    63
#define GRN_EXPR_TOKEN_STRING                         64
#define GRN_EXPR_TOKEN_BOOLEAN                        65
#define GRN_EXPR_TOKEN_NULL                           66
#define GRN_EXPR_TOKEN_BRACKETL                       67
#define GRN_EXPR_TOKEN_BRACKETR                       68
#define GRN_EXPR_TOKEN_DOT                            69
