#define GRN_EXPR_TOKEN_START_OUTPUT_COLUMNS            1
#define GRN_EXPR_TOKEN_LOGICAL_AND                     2
#define GRN_EXPR_TOKEN_LOGICAL_AND_NOT                 3
#define GRN_EXPR_TOKEN_LOGICAL_OR                      4
#define GRN_EXPR_TOKEN_QSTRING                         5
#define GRN_EXPR_TOKEN_PARENL                          6
#define GRN_EXPR_TOKEN_PARENR                          7
#define GRN_EXPR_TOKEN_RELATIVE_OP                     8
#define GRN_EXPR_TOKEN_IDENTIFIER                      9
#define GRN_EXPR_TOKEN_BRACEL                         10
#define GRN_EXPR_TOKEN_BRACER                         11
#define GRN_EXPR_TOKEN_EVAL                           12
#define GRN_EXPR_TOKEN_COMMA                          13
#define GRN_EXPR_TOKEN_ASSIGN                         14
#define GRN_EXPR_TOKEN_STAR_ASSIGN                    15
#define GRN_EXPR_TOKEN_SLASH_ASSIGN                   16
#define GRN_EXPR_TOKEN_MOD_ASSIGN                     17
#define GRN_EXPR_TOKEN_PLUS_ASSIGN                    18
#define GRN_EXPR_TOKEN_MINUS_ASSIGN                   19
#define GRN_EXPR_TOKEN_SHIFTL_ASSIGN                  20
#define GRN_EXPR_TOKEN_SHIFTR_ASSIGN                  21
#define GRN_EXPR_TOKEN_SHIFTRR_ASSIGN                 22
#define GRN_EXPR_TOKEN_AND_ASSIGN                     23
#define GRN_EXPR_TOKEN_XOR_ASSIGN                     24
#define GRN_EXPR_TOKEN_OR_ASSIGN                      25
#define GRN_EXPR_TOKEN_QUESTION                       26
#define GRN_EXPR_TOKEN_COLON                          27
#define GRN_EXPR_TOKEN_BITWISE_OR                     28
#define GRN_EXPR_TOKEN_BITWISE_XOR                    29
#define GRN_EXPR_TOKEN_BITWISE_AND                    30
#define GRN_EXPR_TOKEN_EQUAL                          31
#define GRN_EXPR_TOKEN_NOT_EQUAL                      32
#define GRN_EXPR_TOKEN_LESS                           33
#define GRN_EXPR_TOKEN_GREATER                        34
#define GRN_EXPR_TOKEN_LESS_EQUAL                     35
#define GRN_EXPR_TOKEN_GREATER_EQUAL                  36
#define GRN_EXPR_TOKEN_IN                             37
#define GRN_EXPR_TOKEN_MATCH                          38
#define GRN_EXPR_TOKEN_NEAR                           39
#define GRN_EXPR_TOKEN_NEAR2                          40
#define GRN_EXPR_TOKEN_SIMILAR                        41
#define GRN_EXPR_TOKEN_TERM_EXTRACT                   42
#define GRN_EXPR_TOKEN_LCP                            43
#define GRN_EXPR_TOKEN_PREFIX                         44
#define GRN_EXPR_TOKEN_SUFFIX                         45
#define GRN_EXPR_TOKEN_SHIFTL                         46
#define GRN_EXPR_TOKEN_SHIFTR                         47
#define GRN_EXPR_TOKEN_SHIFTRR                        48
#define GRN_EXPR_TOKEN_PLUS                           49
#define GRN_EXPR_TOKEN_MINUS                          50
#define GRN_EXPR_TOKEN_STAR                           51
#define GRN_EXPR_TOKEN_SLASH                          52
#define GRN_EXPR_TOKEN_MOD                            53
#define GRN_EXPR_TOKEN_DELETE                         54
#define GRN_EXPR_TOKEN_INCR                           55
#define GRN_EXPR_TOKEN_DECR                           56
#define GRN_EXPR_TOKEN_NOT                            57
#define GRN_EXPR_TOKEN_BITWISE_NOT                    58
#define GRN_EXPR_TOKEN_ADJUST                         59
#define GRN_EXPR_TOKEN_EXACT                          60
#define GRN_EXPR_TOKEN_PARTIAL                        61
#define GRN_EXPR_TOKEN_UNSPLIT                        62
#define GRN_EXPR_TOKEN_DECIMAL                        63
#define GRN_EXPR_TOKEN_HEX_INTEGER                    64
#define GRN_EXPR_TOKEN_STRING                         65
#define GRN_EXPR_TOKEN_BOOLEAN                        66
#define GRN_EXPR_TOKEN_NULL                           67
#define GRN_EXPR_TOKEN_BRACKETL                       68
#define GRN_EXPR_TOKEN_BRACKETR                       69
#define GRN_EXPR_TOKEN_DOT                            70
#define GRN_EXPR_TOKEN_NONEXISTENT_COLUMN             71
