#define GRN_EXPR_TOKEN_LOGICAL_AND                     1
#define GRN_EXPR_TOKEN_LOGICAL_BUT                     2
#define GRN_EXPR_TOKEN_LOGICAL_OR                      3
#define GRN_EXPR_TOKEN_QSTRING                         4
#define GRN_EXPR_TOKEN_PARENL                          5
#define GRN_EXPR_TOKEN_PARENR                          6
#define GRN_EXPR_TOKEN_LESS                            7
#define GRN_EXPR_TOKEN_GREATER                         8
#define GRN_EXPR_TOKEN_LESS_EQUAL                      9
#define GRN_EXPR_TOKEN_GREATER_EQUAL                  10
#define GRN_EXPR_TOKEN_IN                             11
#define GRN_EXPR_TOKEN_MATCH                          12
#define GRN_EXPR_TOKEN_NEAR                           13
#define GRN_EXPR_TOKEN_SIMILAR                        14
#define GRN_EXPR_TOKEN_EXTRACT                        15
#define GRN_EXPR_TOKEN_COLUMN                         16
#define GRN_EXPR_TOKEN_BRACEL                         17
#define GRN_EXPR_TOKEN_BRACER                         18
#define GRN_EXPR_TOKEN_EVAL                           19
#define GRN_EXPR_TOKEN_COMMA                          20
#define GRN_EXPR_TOKEN_ASSIGN                         21
#define GRN_EXPR_TOKEN_STAR_ASSIGN                    22
#define GRN_EXPR_TOKEN_SLASH_ASSIGN                   23
#define GRN_EXPR_TOKEN_MOD_ASSIGN                     24
#define GRN_EXPR_TOKEN_PLUS_ASSIGN                    25
#define GRN_EXPR_TOKEN_MINUS_ASSIGN                   26
#define GRN_EXPR_TOKEN_SHIFTL_ASSIGN                  27
#define GRN_EXPR_TOKEN_SHIRTR_ASSIGN                  28
#define GRN_EXPR_TOKEN_SHIFTRR_ASSIGN                 29
#define GRN_EXPR_TOKEN_AND_ASSIGN                     30
#define GRN_EXPR_TOKEN_XOR_ASSIGN                     31
#define GRN_EXPR_TOKEN_OR_ASSIGN                      32
#define GRN_EXPR_TOKEN_QUESTION                       33
#define GRN_EXPR_TOKEN_COLON                          34
#define GRN_EXPR_TOKEN_BITWISE_OR                     35
#define GRN_EXPR_TOKEN_BITWISE_XOR                    36
#define GRN_EXPR_TOKEN_BITWISE_AND                    37
#define GRN_EXPR_TOKEN_EQUAL                          38
#define GRN_EXPR_TOKEN_NOT_EQUAL                      39
#define GRN_EXPR_TOKEN_SHIFTL                         40
#define GRN_EXPR_TOKEN_SHIFTR                         41
#define GRN_EXPR_TOKEN_SHIFTRR                        42
#define GRN_EXPR_TOKEN_PLUS                           43
#define GRN_EXPR_TOKEN_MINUS                          44
#define GRN_EXPR_TOKEN_STAR                           45
#define GRN_EXPR_TOKEN_SLASH                          46
#define GRN_EXPR_TOKEN_MOD                            47
#define GRN_EXPR_TOKEN_DELETE                         48
#define GRN_EXPR_TOKEN_INCR                           49
#define GRN_EXPR_TOKEN_DECR                           50
#define GRN_EXPR_TOKEN_NOT                            51
#define GRN_EXPR_TOKEN_ADJ_INC                        52
#define GRN_EXPR_TOKEN_ADJ_DEC                        53
#define GRN_EXPR_TOKEN_ADJ_NEG                        54
#define GRN_EXPR_TOKEN_IDENTIFIER                     55
#define GRN_EXPR_TOKEN_DECIMAL                        56
#define GRN_EXPR_TOKEN_HEX_INTEGER                    57
#define GRN_EXPR_TOKEN_STRING                         58
#define GRN_EXPR_TOKEN_BOOLEAN                        59
#define GRN_EXPR_TOKEN_NULL                           60
#define GRN_EXPR_TOKEN_BRACKETL                       61
#define GRN_EXPR_TOKEN_BRACKETR                       62
#define GRN_EXPR_TOKEN_RBRACE                         63
#define GRN_EXPR_TOKEN_DOT                            64
