#define GRN_EXPR_TOKEN_COMMA                           1
#define GRN_EXPR_TOKEN_ASSIGN                          2
#define GRN_EXPR_TOKEN_STAR_ASSIGN                     3
#define GRN_EXPR_TOKEN_SLASH_ASSIGN                    4
#define GRN_EXPR_TOKEN_MOD_ASSIGN                      5
#define GRN_EXPR_TOKEN_PLUS_ASSIGN                     6
#define GRN_EXPR_TOKEN_MINUS_ASSIGN                    7
#define GRN_EXPR_TOKEN_SHIFTL_ASSIGN                   8
#define GRN_EXPR_TOKEN_SHIRTR_ASSIGN                   9
#define GRN_EXPR_TOKEN_SHIFTRR_ASSIGN                 10
#define GRN_EXPR_TOKEN_AND_ASSIGN                     11
#define GRN_EXPR_TOKEN_XOR_ASSIGN                     12
#define GRN_EXPR_TOKEN_OR_ASSIGN                      13
#define GRN_EXPR_TOKEN_QUESTION                       14
#define GRN_EXPR_TOKEN_COLON                          15
#define GRN_EXPR_TOKEN_LOGICAL_OR                     16
#define GRN_EXPR_TOKEN_LOGICAL_AND                    17
#define GRN_EXPR_TOKEN_LOGICAL_BUT                    18
#define GRN_EXPR_TOKEN_BITWISE_OR                     19
#define GRN_EXPR_TOKEN_BITWISE_XOR                    20
#define GRN_EXPR_TOKEN_BITWISE_AND                    21
#define GRN_EXPR_TOKEN_EQUAL                          22
#define GRN_EXPR_TOKEN_NOT_EQUAL                      23
#define GRN_EXPR_TOKEN_LESS                           24
#define GRN_EXPR_TOKEN_GREATER                        25
#define GRN_EXPR_TOKEN_LESS_EQUAL                     26
#define GRN_EXPR_TOKEN_GREATER_EQUAL                  27
#define GRN_EXPR_TOKEN_IN                             28
#define GRN_EXPR_TOKEN_MATCH                          29
#define GRN_EXPR_TOKEN_SHIFTL                         30
#define GRN_EXPR_TOKEN_SHIFTR                         31
#define GRN_EXPR_TOKEN_SHIFTRR                        32
#define GRN_EXPR_TOKEN_PLUS                           33
#define GRN_EXPR_TOKEN_MINUS                          34
#define GRN_EXPR_TOKEN_STAR                           35
#define GRN_EXPR_TOKEN_SLASH                          36
#define GRN_EXPR_TOKEN_MOD                            37
#define GRN_EXPR_TOKEN_DELETE                         38
#define GRN_EXPR_TOKEN_INCR                           39
#define GRN_EXPR_TOKEN_DECR                           40
#define GRN_EXPR_TOKEN_NOT                            41
#define GRN_EXPR_TOKEN_ADJ_INC                        42
#define GRN_EXPR_TOKEN_ADJ_DEC                        43
#define GRN_EXPR_TOKEN_ADJ_NEG                        44
#define GRN_EXPR_TOKEN_UNARY_SIMILAR                  45
#define GRN_EXPR_TOKEN_UNARY_EXTRACT                  46
#define GRN_EXPR_TOKEN_UNARY_NEAR                     47
#define GRN_EXPR_TOKEN_PARENL                         48
#define GRN_EXPR_TOKEN_PARENR                         49
#define GRN_EXPR_TOKEN_IDENTIFIER                     50
#define GRN_EXPR_TOKEN_DECIMAL                        51
#define GRN_EXPR_TOKEN_HEX_INTEGER                    52
#define GRN_EXPR_TOKEN_STRING                         53
#define GRN_EXPR_TOKEN_BOOLEAN                        54
#define GRN_EXPR_TOKEN_NULL                           55
#define GRN_EXPR_TOKEN_BRACKETL                       56
#define GRN_EXPR_TOKEN_BRACKETR                       57
#define GRN_EXPR_TOKEN_BRACEL                         58
#define GRN_EXPR_TOKEN_RBRACE                         59
#define GRN_EXPR_TOKEN_DOT                            60
