#define GRN_EXPR_TOKEN_LOGICAL_AND                     1
#define GRN_EXPR_TOKEN_LOGICAL_BUT                     2
#define GRN_EXPR_TOKEN_LOGICAL_OR                      3
#define GRN_EXPR_TOKEN_QSTRING                         4
#define GRN_EXPR_TOKEN_PARENL                          5
#define GRN_EXPR_TOKEN_PARENR                          6
#define GRN_EXPR_TOKEN_RELATIVE_OP                     7
#define GRN_EXPR_TOKEN_IDENTIFIER                      8
#define GRN_EXPR_TOKEN_BRACEL                          9
#define GRN_EXPR_TOKEN_BRACER                         10
#define GRN_EXPR_TOKEN_EVAL                           11
#define GRN_EXPR_TOKEN_COMMA                          12
#define GRN_EXPR_TOKEN_ASSIGN                         13
#define GRN_EXPR_TOKEN_STAR_ASSIGN                    14
#define GRN_EXPR_TOKEN_SLASH_ASSIGN                   15
#define GRN_EXPR_TOKEN_MOD_ASSIGN                     16
#define GRN_EXPR_TOKEN_PLUS_ASSIGN                    17
#define GRN_EXPR_TOKEN_MINUS_ASSIGN                   18
#define GRN_EXPR_TOKEN_SHIFTL_ASSIGN                  19
#define GRN_EXPR_TOKEN_SHIRTR_ASSIGN                  20
#define GRN_EXPR_TOKEN_SHIFTRR_ASSIGN                 21
#define GRN_EXPR_TOKEN_AND_ASSIGN                     22
#define GRN_EXPR_TOKEN_XOR_ASSIGN                     23
#define GRN_EXPR_TOKEN_OR_ASSIGN                      24
#define GRN_EXPR_TOKEN_QUESTION                       25
#define GRN_EXPR_TOKEN_COLON                          26
#define GRN_EXPR_TOKEN_BITWISE_OR                     27
#define GRN_EXPR_TOKEN_BITWISE_XOR                    28
#define GRN_EXPR_TOKEN_BITWISE_AND                    29
#define GRN_EXPR_TOKEN_EQUAL                          30
#define GRN_EXPR_TOKEN_NOT_EQUAL                      31
#define GRN_EXPR_TOKEN_LESS                           32
#define GRN_EXPR_TOKEN_GREATER                        33
#define GRN_EXPR_TOKEN_LESS_EQUAL                     34
#define GRN_EXPR_TOKEN_GREATER_EQUAL                  35
#define GRN_EXPR_TOKEN_IN                             36
#define GRN_EXPR_TOKEN_MATCH                          37
#define GRN_EXPR_TOKEN_NEAR                           38
#define GRN_EXPR_TOKEN_SIMILAR                        39
#define GRN_EXPR_TOKEN_EXTRACT                        40
#define GRN_EXPR_TOKEN_SHIFTL                         41
#define GRN_EXPR_TOKEN_SHIFTR                         42
#define GRN_EXPR_TOKEN_SHIFTRR                        43
#define GRN_EXPR_TOKEN_PLUS                           44
#define GRN_EXPR_TOKEN_MINUS                          45
#define GRN_EXPR_TOKEN_STAR                           46
#define GRN_EXPR_TOKEN_SLASH                          47
#define GRN_EXPR_TOKEN_MOD                            48
#define GRN_EXPR_TOKEN_DELETE                         49
#define GRN_EXPR_TOKEN_INCR                           50
#define GRN_EXPR_TOKEN_DECR                           51
#define GRN_EXPR_TOKEN_NOT                            52
#define GRN_EXPR_TOKEN_ADJ_INC                        53
#define GRN_EXPR_TOKEN_ADJ_DEC                        54
#define GRN_EXPR_TOKEN_ADJ_NEG                        55
#define GRN_EXPR_TOKEN_DECIMAL                        56
#define GRN_EXPR_TOKEN_HEX_INTEGER                    57
#define GRN_EXPR_TOKEN_STRING                         58
#define GRN_EXPR_TOKEN_BOOLEAN                        59
#define GRN_EXPR_TOKEN_NULL                           60
#define GRN_EXPR_TOKEN_BRACKETL                       61
#define GRN_EXPR_TOKEN_BRACKETR                       62
#define GRN_EXPR_TOKEN_RBRACE                         63
#define GRN_EXPR_TOKEN_DOT                            64
