#define GRN_EXPR_TOKEN_START_OUTPUT_COLUMNS             1
#define GRN_EXPR_TOKEN_START_ADJUSTER                   2
#define GRN_EXPR_TOKEN_START_SORT_KEYS                  3
#define GRN_EXPR_TOKEN_START_OPTIONS                    4
#define GRN_EXPR_TOKEN_LOGICAL_AND                      5
#define GRN_EXPR_TOKEN_LOGICAL_AND_NOT                  6
#define GRN_EXPR_TOKEN_LOGICAL_OR                       7
#define GRN_EXPR_TOKEN_NEGATIVE                         8
#define GRN_EXPR_TOKEN_QSTRING                          9
#define GRN_EXPR_TOKEN_PARENL                          10
#define GRN_EXPR_TOKEN_PARENR                          11
#define GRN_EXPR_TOKEN_ADJUST                          12
#define GRN_EXPR_TOKEN_RELATIVE_OP                     13
#define GRN_EXPR_TOKEN_IDENTIFIER                      14
#define GRN_EXPR_TOKEN_BRACEL                          15
#define GRN_EXPR_TOKEN_BRACER                          16
#define GRN_EXPR_TOKEN_EVAL                            17
#define GRN_EXPR_TOKEN_COMMA                           18
#define GRN_EXPR_TOKEN_ASSIGN                          19
#define GRN_EXPR_TOKEN_STAR_ASSIGN                     20
#define GRN_EXPR_TOKEN_SLASH_ASSIGN                    21
#define GRN_EXPR_TOKEN_MOD_ASSIGN                      22
#define GRN_EXPR_TOKEN_PLUS_ASSIGN                     23
#define GRN_EXPR_TOKEN_MINUS_ASSIGN                    24
#define GRN_EXPR_TOKEN_SHIFTL_ASSIGN                   25
#define GRN_EXPR_TOKEN_SHIFTR_ASSIGN                   26
#define GRN_EXPR_TOKEN_SHIFTRR_ASSIGN                  27
#define GRN_EXPR_TOKEN_AND_ASSIGN                      28
#define GRN_EXPR_TOKEN_XOR_ASSIGN                      29
#define GRN_EXPR_TOKEN_OR_ASSIGN                       30
#define GRN_EXPR_TOKEN_QUESTION                        31
#define GRN_EXPR_TOKEN_COLON                           32
#define GRN_EXPR_TOKEN_BITWISE_OR                      33
#define GRN_EXPR_TOKEN_BITWISE_XOR                     34
#define GRN_EXPR_TOKEN_BITWISE_AND                     35
#define GRN_EXPR_TOKEN_EQUAL                           36
#define GRN_EXPR_TOKEN_NOT_EQUAL                       37
#define GRN_EXPR_TOKEN_LESS                            38
#define GRN_EXPR_TOKEN_GREATER                         39
#define GRN_EXPR_TOKEN_LESS_EQUAL                      40
#define GRN_EXPR_TOKEN_GREATER_EQUAL                   41
#define GRN_EXPR_TOKEN_IN                              42
#define GRN_EXPR_TOKEN_MATCH                           43
#define GRN_EXPR_TOKEN_NEAR                            44
#define GRN_EXPR_TOKEN_NEAR2                           45
#define GRN_EXPR_TOKEN_NEAR_PHRASE                     46
#define GRN_EXPR_TOKEN_ORDERED_NEAR_PHRASE             47
#define GRN_EXPR_TOKEN_SIMILAR                         48
#define GRN_EXPR_TOKEN_TERM_EXTRACT                    49
#define GRN_EXPR_TOKEN_QUORUM                          50
#define GRN_EXPR_TOKEN_LCP                             51
#define GRN_EXPR_TOKEN_PREFIX                          52
#define GRN_EXPR_TOKEN_SUFFIX                          53
#define GRN_EXPR_TOKEN_REGEXP                          54
#define GRN_EXPR_TOKEN_SHIFTL                          55
#define GRN_EXPR_TOKEN_SHIFTR                          56
#define GRN_EXPR_TOKEN_SHIFTRR                         57
#define GRN_EXPR_TOKEN_PLUS                            58
#define GRN_EXPR_TOKEN_MINUS                           59
#define GRN_EXPR_TOKEN_STAR                            60
#define GRN_EXPR_TOKEN_SLASH                           61
#define GRN_EXPR_TOKEN_MOD                             62
#define GRN_EXPR_TOKEN_DELETE                          63
#define GRN_EXPR_TOKEN_INCR                            64
#define GRN_EXPR_TOKEN_DECR                            65
#define GRN_EXPR_TOKEN_NOT                             66
#define GRN_EXPR_TOKEN_BITWISE_NOT                     67
#define GRN_EXPR_TOKEN_EXACT                           68
#define GRN_EXPR_TOKEN_PARTIAL                         69
#define GRN_EXPR_TOKEN_UNSPLIT                         70
#define GRN_EXPR_TOKEN_DECIMAL                         71
#define GRN_EXPR_TOKEN_HEX_INTEGER                     72
#define GRN_EXPR_TOKEN_STRING                          73
#define GRN_EXPR_TOKEN_BOOLEAN                         74
#define GRN_EXPR_TOKEN_NULL                            75
#define GRN_EXPR_TOKEN_BRACKETL                        76
#define GRN_EXPR_TOKEN_BRACKETR                        77
#define GRN_EXPR_TOKEN_DOT                             78
#define GRN_EXPR_TOKEN_NONEXISTENT_COLUMN              79
