#!/usr/bin/env ruby

#%# family=auto
#%# capabilities=autoconf suggest

require 'net/http'
begin
  require 'json'
rescue LoadError
  require 'rubygems'
  require 'json'
end

label = ENV["label"]
@groonga = ENV["groonga"] || "groonga"
@default_host = ENV["host"] || "127.0.0.1"
@default_http_port = 10041
@default_gqtp_port = 10043

command = ARGV.shift

def parse(success, result)
  if success
    begin
      status, body = JSON.parse(result)
      return_code, start_time, elapsed, error_message = status
      if return_code.zero?
        [success, body]
      else
        [false, error_message]
      end
    rescue JSON::ParserError
      [false, $!.message]
    end
  else
    [success, result]
  end
end

def run_http(host, port, command)
  path = "/d/#{command}"
  begin
    response = Net::HTTP.start(host, port) do |http|
      http.get(path)
    end
  rescue SystemCallError, TimeoutError
    return [false, "#{$!.class}: #{$!}"]
  end
  if response.is_a?(Net::HTTPSuccess)
    parse(true, response.body)
  else
    [false, "#{response.code}: #{response.body}"]
  end
end

def run_gqtp(host, port, command)
  groonga = "#{@groonga} -p #{port} -c #{host}"
  result = `#{groonga} #{command} 2>&1`
  parse($?.success?, result)
end

def run(command)
  case @service_type
  when "http"
    run_http(@http_host, @http_port, command)
  when "httpd"
    run_http(@httpd_host, @httpd_port, command)
  when "gqtp"
    run_gqtp(@gqtp_host, @gqtp_port, command)
  else
    [false, "unknown service type: #{@service_type}"]
  end
end

def setup_service_type
  if /_([^_]+)\z/ =~ $0
    @service_type = $1
  else
    @service_type = nil
  end
end

def setup_http
  @http_host = ENV["http_host"] || @default_host
  @http_port = (ENV["http_port"] || @default_http_port).to_i
  @http_pid_path = File.exist?(ENV["http_pid_path"]) || nil
end

def setup_httpd
  @httpd_host = ENV["httpd_host"] || @default_host
  @httpd_port = (ENV["httpd_port"] || @default_http_port).to_i
  @httpd_pid_path = File.exist?(ENV["httpd_pid_path"]) || nil
end

def setup_gqtp
  @gqtp_host = ENV["gqtp_host"] || @default_host
  @gqtp_port = (ENV["gqtp_port"] || @default_gqtp_port).to_i
  @gqtp_pid_path = File.exist?(ENV["gqtp_pid_path"]) || nil
end

def setup
  setup_service_type
  setup_http
  setup_httpd
  setup_gqtp
end

def pid_files_esists?
  pid_path_variable_names = [
    "pid_path",
    "pid_file", # For backward compatibility. Remove me when 5.0.0.
    "http_pid_path",
    "httpd_pid_path",
    "gqtp_pid_path",
  ]
  pid_paths = pid_path_variable_names.collect do |variable_name|
    ENV[variable_name]
  end
  pid_paths = pid_paths.compact
  if pid_paths.empty?
    variable_names = pid_path_variable_names.collect do |name|
      "env.#{name}"
    end
    variable_names_label = variable_names[0..-2].join(", ")
    variable_names_label << " and/or #{variable_names.last}"
    puts("no (No PID path is specified. Specify #{variable_names_label}.)")
    return false
  end
  pid_paths.each do |pid_path|
    next unless File.exist?(pid_path)
    return true
  end
  pid_paths_label = pid_paths.join(", ")
  puts("no (All PID paths don't exist: #{pid_paths_label})")
  return false
end

def autoconf
  exit(false) unless pid_files_esists?

  results = []

  if @http_host and @http_port
    results << run_http(@http_host, @http_port, "status")
  end

  if @httpd_host and @httpd_port
    results << run_http(@httpd_host, @httpd_port, "status")
  end

  if @gqtp_host and @gqtp_port
    results << run_gqtp(@gqtp_host, @gqtp_port, "status")
  end

  if results.any? {|success, _| success}
    puts("yes")
    exit(true)
  else
    errors = results.collect do |_, result|
      result
    end
    error_detail = errors.join(", ")
    puts("no (#{error_detail})")
    exit(false)
  end
end

def suggest
  exit(false) unless pid_files_esists?

  if @http_host and @http_port and @http_pid_path
    success, _ = run_http(@http_host, @http_port, "status")
    puts("http") if success
  end
  if @httpd_host and @httpd_port and @httpd_pid_path
    success, _ = run_http(@httpd_host, @httpd_port, "status")
    puts("httpd") if success
  end
  if @gqtp_host and @gqtp_port and @gqtp_pid_path
    success, _ = run_gqtp(@gqtp_host, @gqtp_port, "status")
    puts("gqtp") if success
  end
  exit(true)
end

setup
case command
when "autoconf", "detect"
  autoconf
when "suggest"
  suggest
when "config"
  if label.nil?
    title = "groonga: throughput"
  else
    title = "groonga: #{label}: throughput"
  end
  puts(<<EOF)
graph_title #{title}
graph_vlabel queries per ${graph_period}
graph_category groonga
graph_info groonga throughput

n_queries.label N queries
n_queries.type COUNTER
EOF
  exit(true)
end

success, body = run("status")
unless success
  puts("error: #{body}")
  exit(false)
end
puts(<<EOF)
n_queries.value #{body["n_queries"]}
EOF
