FROM ubuntu:18.04

ENV DEBIAN_FRONTEND=noninteractive

RUN \
  apt update -qq && \
  apt install -qq -y \
    bison \
    g++ \
    gcc \
    gdb \
    git \
    libevent-dev \
    liblz4-dev \
    libmecab-dev \
    libmsgpack-dev \
    libssl-dev \
    libstemmer-dev \
    libzmq3-dev \
    libzstd-dev \
    make \
    mecab-naist-jdic \
    pkg-config \
    rsync \
    ruby \
    ruby-dev \
    sudo \
    tzdata \
    zlib1g-dev

# RUN \
#   apt update -qq && \
#   apt install -qq -y software-properties-common && \
#   add-apt-repository -y ppa:cutter-testing-framework/ppa && \
#   apt update -qq && \
#   apt install -qq -y cutter-testing-framework

RUN \
  gem install \
    bundler \
    groonga-client \
    pkg-config \
    test-unit

RUN \
  useradd --user-group --create-home groonga

RUN \
  echo "groonga ALL=(ALL:ALL) NOPASSWD:ALL" | \
    EDITOR=tee visudo -f /etc/sudoers.d/groonga

COPY . /home/groonga/source

USER groonga

WORKDIR /home/groonga
RUN mkdir -p build
WORKDIR /home/groonga/build

RUN ../source/configure \
  --prefix=/tmp/local \
  --enable-debug \
  --with-ruby \
  --enable-mruby

RUN make -j$(nproc) > /dev/null

RUN \
  mkdir -p /tmp/local/var/log/groonga/httpd/

RUN \
  rsync -a --include "*.rb" --include "*/" --exclude "*" \
    ../source/plugins/ \
    plugins/

RUN \
  mkdir -p test/command && \
  rsync -a --delete \
    ../source/test/command/suite/ \
    test/command/suite/

CMD \
  # BUILD_DIR=test/unit \
  #   ../source/test/unit/run-test.sh && \
  BUILD_DIR=test/mruby \
    ../source/test/mruby/run-test.rb && \
  BUILD_DIR=test/command_line \
    ../source/test/command_line/run-test.rb && \
  BUILD_DIR=test/command \
    ../source/test/command/run-test.sh \
    test/command/suite \
    --reporter mark && \
  BUILD_DIR=test/command \
    ../source/test/command/run-test.sh \
    test/command/suite \
    --reporter mark \
    --interface http && \
  BUILD_DIR=test/command \
    ../source/test/command/run-test.sh \
    test/command/suite \
    --reporter mark \
    --testee groonga-httpd \
    --n-workers 2
