name: Debian

# WIP
on:
  - push
  - pull_request

#on:
#  schedule:
#    - cron:  '0 0 * * *'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Install dependencies
        run: |
          sudo apt -V install \
            autoconf-archive \
            bison \
            devscripts \
            python3-pip \
            ruby
      - name: Install Sphinx
        run: |
          sudo pip3 install -v sphinx
      - name: Clone dependencies
        run: |
          cd ..
          git clone --depth 1 https://github.com/apache/arrow.git
          git clone --depth 1 https://github.com/groonga/groonga.org.git
      - name: Generate configure
        run: |
          ./autogen.sh
      - name: Configure for archive
        run: |
          ./configure \
            --enable-document \
            --enable-mruby \
            --with-groonga-org-path=../groonga.org \
            --with-ruby
      - name: Build archive
        run: |
          make dist
      - name: Setup debian/changelog
        run: |
          cd packages
          dch --newversion $(cat ../base_version)-1 "New upstream version"
      - name: Build with docker
        run: |
          cd packages
          rake apt:build
        env:
          APACHE_ARROW_REPOSITORY: ../../arrow
          APT_TARGETS: debian-buster
